# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ekinnune <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/20 15:29:24 by ekinnune          #+#    #+#              #
#    Updated: 2020/02/20 15:46:53 by ekinnune         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

EXE = ft_display_file

GCCFLAGS = -Wall -Wextra -Werror -o

all: 
	gcc $(GCCFLAGS) $(EXE) *.c

clean:
	rm $(EXE)

fclean: clean
	rm *.c
