# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ekinnune <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/18 22:12:35 by ekinnune          #+#    #+#              #
#    Updated: 2020/02/18 22:15:57 by ekinnune         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILES = math_funcs.c main.c print_and_convert.c

compile:
	gcc $(FILES) -o do-op

all: compile

clean:
	rm *.c
